'use client';
  // This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { useState, useEffect, useCallback, useRef } from 'react';
import HeaderLogo from 'src/components/Header/headerLogo';
import HeaderNav from 'src/components/Header/headerNav';
import client from 'src/lib/sitecore-client';
import { CdpHelper, useSitecore } from '@sitecore-content-sdk/nextjs';
import { pageView } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';
import CarouselPanel from 'src/components/Carousel/carouselPanel';
import CarouselControls from 'src/components/Carousel/carouselControls';
import CarouselIndicators from 'src/components/Carousel/carouselIndicators';
import AccordionItem from 'src/components/Accordion/accordionItem';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useEffect', value: useEffect },
      { name: 'useCallback', value: useCallback },
      { name: 'useRef', value: useRef },
    ]
  },
  {
    module: 'src/components/Header/headerLogo',
    exports: [
      { name: 'default', value: HeaderLogo },
    ]
  },
  {
    module: 'src/components/Header/headerNav',
    exports: [
      { name: 'default', value: HeaderNav },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'useSitecore', value: useSitecore },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: 'src/components/Carousel/carouselPanel',
    exports: [
      { name: 'default', value: CarouselPanel },
    ]
  },
  {
    module: 'src/components/Carousel/carouselControls',
    exports: [
      { name: 'default', value: CarouselControls },
    ]
  },
  {
    module: 'src/components/Carousel/carouselIndicators',
    exports: [
      { name: 'default', value: CarouselIndicators },
    ]
  },
  {
    module: 'src/components/Accordion/accordionItem',
    exports: [
      { name: 'default', value: AccordionItem },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
