// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultServerImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { Image, Link, RichText, AppPlaceholder } from '@sitecore-content-sdk/nextjs';
import TeaserImage from 'src/components/Teaser/teaserImage';
import TeaserActions from 'src/components/Teaser/teaserActions';
import FooterLogo from 'src/components/SiteFooter/footerLogo';
import FooterNav from 'src/components/SiteFooter/footerNav';
import FooterSocialLinks from 'src/components/SiteFooter/footerSocialLinks';
import NextLink from 'next/link';
import PromoCard from 'src/components/PromoCardGrid/promoCard';
import React from 'react';
import componentMap from '.sitecore/component-map';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Image', value: Image },
      { name: 'Link', value: Link },
      { name: 'RichText', value: RichText },
      { name: 'AppPlaceholder', value: AppPlaceholder },
    ]
  },
  {
    module: 'src/components/Teaser/teaserImage',
    exports: [
      { name: 'default', value: TeaserImage },
    ]
  },
  {
    module: 'src/components/Teaser/teaserActions',
    exports: [
      { name: 'default', value: TeaserActions },
    ]
  },
  {
    module: 'src/components/SiteFooter/footerLogo',
    exports: [
      { name: 'default', value: FooterLogo },
    ]
  },
  {
    module: 'src/components/SiteFooter/footerNav',
    exports: [
      { name: 'default', value: FooterNav },
    ]
  },
  {
    module: 'src/components/SiteFooter/footerSocialLinks',
    exports: [
      { name: 'default', value: FooterSocialLinks },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: NextLink },
    ]
  },
  {
    module: 'src/components/PromoCardGrid/promoCard',
    exports: [
      { name: 'default', value: PromoCard },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'default', value: React },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultServerImportEntries, importMap);
