// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultServerImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs } from 'react/jsx-runtime';
import React from 'react';
import componentMap from '.sitecore/component-map';
import { AppPlaceholder, Link, Image } from '@sitecore-content-sdk/nextjs';
import NextLink from 'next/link';
import FooterLogo from 'src/components/SiteFooter/footerLogo';
import FooterNav from 'src/components/SiteFooter/footerNav';
import FooterSocialLinks from 'src/components/SiteFooter/footerSocialLinks';
import PromoCard from 'src/components/PromoCardGrid/promoCard';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'default', value: React },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'Link', value: Link },
      { name: 'Image', value: Image },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: NextLink },
    ]
  },
  {
    module: 'src/components/SiteFooter/footerLogo',
    exports: [
      { name: 'default', value: FooterLogo },
    ]
  },
  {
    module: 'src/components/SiteFooter/footerNav',
    exports: [
      { name: 'default', value: FooterNav },
    ]
  },
  {
    module: 'src/components/SiteFooter/footerSocialLinks',
    exports: [
      { name: 'default', value: FooterSocialLinks },
    ]
  },
  {
    module: 'src/components/PromoCardGrid/promoCard',
    exports: [
      { name: 'default', value: PromoCard },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultServerImportEntries, importMap);
